# Generated by Django 5.2 on 2025-11-11 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nombre de la base de datos')),
                ('alias', models.CharField(max_length=100, unique=True, verbose_name='Alias de conexión')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Base de datos',
                'verbose_name_plural': 'Bases de datos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('schema_name', models.CharField(default='public', max_length=255, verbose_name='Esquema')),
                ('table_name', models.CharField(max_length=255, verbose_name='Nombre de la tabla')),
                ('table_type', models.CharField(default='BASE TABLE', max_length=50, verbose_name='Tipo de tabla')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('row_count', models.BigIntegerField(blank=True, null=True, verbose_name='Número de filas')),
                ('database', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='core.database', verbose_name='Base de datos')),
            ],
            options={
                'verbose_name': 'Tabla',
                'verbose_name_plural': 'Tablas',
                'ordering': ['schema_name', 'table_name'],
                'unique_together': {('database', 'schema_name', 'table_name')},
            },
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('column_name', models.CharField(max_length=255, verbose_name='Nombre de la columna')),
                ('ordinal_position', models.IntegerField(verbose_name='Posición ordinal')),
                ('data_type', models.CharField(max_length=100, verbose_name='Tipo de dato')),
                ('character_maximum_length', models.IntegerField(blank=True, null=True, verbose_name='Longitud máxima de caracteres')),
                ('numeric_precision', models.IntegerField(blank=True, null=True, verbose_name='Precisión numérica')),
                ('numeric_scale', models.IntegerField(blank=True, null=True, verbose_name='Escala numérica')),
                ('is_nullable', models.BooleanField(default=True, verbose_name='Permite NULL')),
                ('column_default', models.TextField(blank=True, null=True, verbose_name='Valor por defecto')),
                ('is_primary_key', models.BooleanField(default=False, verbose_name='Es llave primaria')),
                ('is_foreign_key', models.BooleanField(default=False, verbose_name='Es llave foránea')),
                ('foreign_table', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tabla referenciada')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='core.table', verbose_name='Tabla')),
            ],
            options={
                'verbose_name': 'Columna',
                'verbose_name_plural': 'Columnas',
                'ordering': ['table', 'ordinal_position'],
                'unique_together': {('table', 'column_name')},
            },
        ),
    ]
