# Generated by Django 5.2 on 2025-11-11 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del reporte')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('orientation', models.CharField(choices=[('vertical', 'Vertical'), ('horizontal', 'Horizontal')], default='vertical', max_length=20, verbose_name='Orientación')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.table', verbose_name='Tabla')),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReportColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('display_name', models.CharField(blank=True, help_text='Nombre personalizado para la columna en el reporte. Si se deja vacío, se usa el nombre de la columna.', max_length=255, null=True, verbose_name='Nombre a mostrar')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Visible')),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_columns', to='core.column', verbose_name='Columna')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_columns', to='core.report', verbose_name='Reporte')),
            ],
            options={
                'verbose_name': 'Columna del reporte',
                'verbose_name_plural': 'Columnas del reporte',
                'ordering': ['report', 'order'],
                'unique_together': {('report', 'column')},
            },
        ),
    ]
