# Generated by Django 5.2 on 2026-02-27 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcolumn',
            name='summary_avg',
            field=models.BooleanField(default=False, verbose_name='Promedio en PDF'),
        ),
        migrations.AddField(
            model_name='reportcolumn',
            name='summary_max',
            field=models.BooleanField(default=False, verbose_name='Máximo en PDF'),
        ),
        migrations.AddField(
            model_name='reportcolumn',
            name='summary_min',
            field=models.BooleanField(default=False, verbose_name='Mínimo en PDF'),
        ),
    ]
