# Generated by Django 5.2 on 2025-11-12 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_report_reportcolumn'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcolumn',
            name='format',
            field=models.CharField(choices=[('text', 'Texto'), ('number', 'Número'), ('date', 'Fecha'), ('datetime', 'Fecha y hora'), ('boolean', 'Booleano'), ('currency', 'Moneda')], default='text', max_length=20, verbose_name='Formato'),
        ),
    ]
