# Generated by Django 5.2 on 2026-03-04 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_reportcolumn_summary_avg_reportcolumn_summary_max_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='interval',
            field=models.CharField(choices=[('all', 'Todos'), ('5', '5 minutos'), ('10', '10 minutos'), ('15', '15 minutos'), ('30', '30 minutos'), ('60', '60 minutos'), ('120', '2 horas'), ('360', '6 horas')], default='all', max_length=10, verbose_name='Intervalo'),
        ),
    ]
