# Generated by Django 5.2 on 2025-11-13 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_reportcolumn_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='interval',
            field=models.CharField(choices=[('all', 'Todos'), ('5', '5 minutos'), ('10', '10 minutos'), ('15', '15 minutos'), ('30', '30 minutos'), ('60', '60 minutos')], default='all', max_length=10, verbose_name='Intervalo'),
        ),
        migrations.AddField(
            model_name='report',
            name='order',
            field=models.CharField(blank=True, choices=[('asc', 'Ascendente'), ('desc', 'Descendente')], default='asc', max_length=10, verbose_name='Tipo de orden'),
        ),
        migrations.AddField(
            model_name='report',
            name='order_by',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Ordenar por'),
        ),
    ]
