# Generated by Django 5.2 on 2025-11-13 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_report_interval_report_order_report_order_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='order_by',
        ),
        migrations.AddField(
            model_name='reportcolumn',
            name='interval',
            field=models.BooleanField(default=False, verbose_name='Intervalo'),
        ),
        migrations.AddField(
            model_name='reportcolumn',
            name='order_by',
            field=models.BooleanField(default=False, verbose_name='Ordenar por'),
        ),
    ]
