# Generated by Django 5.2 on 2025-11-13 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_report_order_by_reportcolumn_interval_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportcolumn',
            name='interval',
        ),
    ]
