# Generated by Django 5.2 on 2025-11-14 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_reportcolumn_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcolumn',
            name='aggregate',
            field=models.CharField(choices=[('none', 'Ninguna (Primer valor)'), ('sum', 'Suma'), ('avg', 'Promedio'), ('min', 'Mínimo'), ('max', 'Máximo'), ('count', 'Contar')], default='none', help_text='Función a aplicar cuando se agrupa por intervalos', max_length=10, verbose_name='Función de agregación'),
        ),
    ]
