FROM python:3.12.10-slim
LABEL maintainer="galejandromorera@gmail.com"

# set environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Install system dependencies
RUN apt-get clean && \
    apt-get update -y && \
    apt-get install -y gettext wget fontconfig libfreetype6 libjpeg62-turbo \
        libpng16-16 libx11-6 libxcb1 libxext6 libxrender1 xfonts-75dpi \
        xfonts-base && \
    wget -q https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6.1-3/wkhtmltox_0.12.6.1-3.bookworm_$(dpkg --print-architecture).deb -O /tmp/wkhtmltox.deb && \
    apt-get install -y /tmp/wkhtmltox.deb && \
    pip install --upgrade pip && \
    rm -rf /var/lib/apt/lists/* /tmp/*

# Create non-root user
RUN adduser --disabled-password --no-create-home app-user

# Create necessary directories
RUN mkdir -p /app/media /app/static && \
    chown -R app-user:app-user /app && \
    chmod -R 755 /app